{
  "name": "ла",
  "description": "Imported database from sql server 'analytics-db-server.database.windows.net' and database 'analytics_db'",
  "compatibilityLevel": 1000000,
  "model": {
    "name": "MBased",
    "description": "A Tabular data model at the 1400 compatibility level.",
    "defaultMode": "directQuery",
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SqlServer analytics-db-server.database.windows.net analytics_db",
        "description": "A data source definition that uses explicit sql server credentials from connection string",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "analytics-db-server.database.windows.net",
            "database": "analytics_db"
          }
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "analytics_admin",
          "EncryptConnection": true,
          "Password": null
        }
      }
    ],
    "tables": [
      {
        "name": "SalesLT.Address",
        "description": "All data from SalesLT.Address",
        "columns": [
          {
            "name": "AddressID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "AddressID"
          },
          {
            "name": "AddressLine1",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "AddressLine1",
            "displayOrdinal": 1
          },
          {
            "name": "AddressLine2",
            "dataType": "string",
            "sourceColumn": "AddressLine2",
            "displayOrdinal": 2
          },
          {
            "name": "City",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "City",
            "displayOrdinal": 3
          },
          {
            "name": "StateProvince",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "StateProvince",
            "displayOrdinal": 4
          },
          {
            "name": "CountryRegion",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "CountryRegion",
            "displayOrdinal": 5
          },
          {
            "name": "PostalCode",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "PostalCode",
            "displayOrdinal": 6
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 7
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 8
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.Address",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_Address\" = Source{[Schema=\"SalesLT\",Item=\"Address\"]}[Data] ",
                "in ",
                "#\"SalesLT_Address\""
              ]
            }
          }
        ]
      },
      {
        "name": "BuildVersion",
        "description": "All data from BuildVersion",
        "columns": [
          {
            "name": "SystemInformationID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "SystemInformationID"
          },
          {
            "name": "Database Version",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Database Version",
            "displayOrdinal": 1
          },
          {
            "name": "VersionDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "VersionDate",
            "displayOrdinal": 2
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 3
          }
        ],
        "partitions": [
          {
            "name": "BuildVersion",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"dbo_BuildVersion\" = Source{[Schema=\"dbo\",Item=\"BuildVersion\"]}[Data] ",
                "in ",
                "#\"dbo_BuildVersion\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.Customer",
        "description": "All data from SalesLT.Customer",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "CustomerID"
          },
          {
            "name": "NameStyle",
            "dataType": "boolean",
            "isNullable": false,
            "sourceColumn": "NameStyle",
            "displayOrdinal": 1
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title",
            "displayOrdinal": 2
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "FirstName",
            "displayOrdinal": 3
          },
          {
            "name": "MiddleName",
            "dataType": "string",
            "sourceColumn": "MiddleName",
            "displayOrdinal": 4
          },
          {
            "name": "LastName",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "LastName",
            "displayOrdinal": 5
          },
          {
            "name": "Suffix",
            "dataType": "string",
            "sourceColumn": "Suffix",
            "displayOrdinal": 6
          },
          {
            "name": "CompanyName",
            "dataType": "string",
            "sourceColumn": "CompanyName",
            "displayOrdinal": 7
          },
          {
            "name": "SalesPerson",
            "dataType": "string",
            "sourceColumn": "SalesPerson",
            "displayOrdinal": 8
          },
          {
            "name": "EmailAddress",
            "dataType": "string",
            "sourceColumn": "EmailAddress",
            "displayOrdinal": 9
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone",
            "displayOrdinal": 10
          },
          {
            "name": "PasswordHash",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "PasswordHash",
            "displayOrdinal": 11
          },
          {
            "name": "PasswordSalt",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "PasswordSalt",
            "displayOrdinal": 12
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 13
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 14
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.Customer",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_Customer\" = Source{[Schema=\"SalesLT\",Item=\"Customer\"]}[Data] ",
                "in ",
                "#\"SalesLT_Customer\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.CustomerAddress",
        "description": "All data from SalesLT.CustomerAddress",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "CustomerID"
          },
          {
            "name": "AddressID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "AddressID",
            "displayOrdinal": 1
          },
          {
            "name": "AddressType",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "AddressType",
            "displayOrdinal": 2
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 3
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.CustomerAddress",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_CustomerAddress\" = Source{[Schema=\"SalesLT\",Item=\"CustomerAddress\"]}[Data] ",
                "in ",
                "#\"SalesLT_CustomerAddress\""
              ]
            }
          }
        ]
      },
      {
        "name": "ErrorLog",
        "description": "All data from ErrorLog",
        "columns": [
          {
            "name": "ErrorLogID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ErrorLogID"
          },
          {
            "name": "ErrorTime",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ErrorTime",
            "displayOrdinal": 1
          },
          {
            "name": "UserName",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "UserName",
            "displayOrdinal": 2
          },
          {
            "name": "ErrorNumber",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ErrorNumber",
            "displayOrdinal": 3
          },
          {
            "name": "ErrorSeverity",
            "dataType": "int64",
            "sourceColumn": "ErrorSeverity",
            "displayOrdinal": 4
          },
          {
            "name": "ErrorState",
            "dataType": "int64",
            "sourceColumn": "ErrorState",
            "displayOrdinal": 5
          },
          {
            "name": "ErrorProcedure",
            "dataType": "string",
            "sourceColumn": "ErrorProcedure",
            "displayOrdinal": 6
          },
          {
            "name": "ErrorLine",
            "dataType": "int64",
            "sourceColumn": "ErrorLine",
            "displayOrdinal": 7
          },
          {
            "name": "ErrorMessage",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "ErrorMessage",
            "displayOrdinal": 8
          }
        ],
        "partitions": [
          {
            "name": "ErrorLog",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"dbo_ErrorLog\" = Source{[Schema=\"dbo\",Item=\"ErrorLog\"]}[Data] ",
                "in ",
                "#\"dbo_ErrorLog\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.Product",
        "description": "All data from SalesLT.Product",
        "columns": [
          {
            "name": "ProductID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ProductID"
          },
          {
            "name": "Name",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Name",
            "displayOrdinal": 1
          },
          {
            "name": "ProductNumber",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "ProductNumber",
            "displayOrdinal": 2
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "displayOrdinal": 3
          },
          {
            "name": "StandardCost",
            "dataType": "decimal",
            "isNullable": false,
            "sourceColumn": "StandardCost",
            "displayOrdinal": 4
          },
          {
            "name": "ListPrice",
            "dataType": "decimal",
            "isNullable": false,
            "sourceColumn": "ListPrice",
            "displayOrdinal": 5
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size",
            "displayOrdinal": 6
          },
          {
            "name": "Weight",
            "dataType": "decimal",
            "sourceColumn": "Weight",
            "displayOrdinal": 7
          },
          {
            "name": "ProductCategoryID",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryID",
            "displayOrdinal": 8
          },
          {
            "name": "ProductModelID",
            "dataType": "int64",
            "sourceColumn": "ProductModelID",
            "displayOrdinal": 9
          },
          {
            "name": "SellStartDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "SellStartDate",
            "displayOrdinal": 10
          },
          {
            "name": "SellEndDate",
            "dataType": "dateTime",
            "sourceColumn": "SellEndDate",
            "displayOrdinal": 11
          },
          {
            "name": "DiscontinuedDate",
            "dataType": "dateTime",
            "sourceColumn": "DiscontinuedDate",
            "displayOrdinal": 12
          },
          {
            "name": "ThumbNailPhoto",
            "dataType": "binary",
            "sourceColumn": "ThumbNailPhoto",
            "displayOrdinal": 13
          },
          {
            "name": "ThumbnailPhotoFileName",
            "dataType": "string",
            "sourceColumn": "ThumbnailPhotoFileName",
            "displayOrdinal": 14
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 15
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 16
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.Product",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_Product\" = Source{[Schema=\"SalesLT\",Item=\"Product\"]}[Data] ",
                "in ",
                "#\"SalesLT_Product\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.ProductCategory",
        "description": "All data from SalesLT.ProductCategory",
        "columns": [
          {
            "name": "ProductCategoryID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ProductCategoryID"
          },
          {
            "name": "ParentProductCategoryID",
            "dataType": "int64",
            "sourceColumn": "ParentProductCategoryID",
            "displayOrdinal": 1
          },
          {
            "name": "Name",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Name",
            "displayOrdinal": 2
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 3
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.ProductCategory",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_ProductCategory\" = Source{[Schema=\"SalesLT\",Item=\"ProductCategory\"]}[Data] ",
                "in ",
                "#\"SalesLT_ProductCategory\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.ProductDescription",
        "description": "All data from SalesLT.ProductDescription",
        "columns": [
          {
            "name": "ProductDescriptionID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ProductDescriptionID"
          },
          {
            "name": "Description",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Description",
            "displayOrdinal": 1
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 2
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 3
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.ProductDescription",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_ProductDescription\" = Source{[Schema=\"SalesLT\",Item=\"ProductDescription\"]}[Data] ",
                "in ",
                "#\"SalesLT_ProductDescription\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.ProductModel",
        "description": "All data from SalesLT.ProductModel",
        "columns": [
          {
            "name": "ProductModelID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ProductModelID"
          },
          {
            "name": "Name",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Name",
            "displayOrdinal": 1
          },
          {
            "name": "CatalogDescription",
            "dataType": "string",
            "sourceColumn": "CatalogDescription",
            "displayOrdinal": 2
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 3
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.ProductModel",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_ProductModel\" = Source{[Schema=\"SalesLT\",Item=\"ProductModel\"]}[Data] ",
                "in ",
                "#\"SalesLT_ProductModel\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.ProductModelProductDescription",
        "description": "All data from SalesLT.ProductModelProductDescription",
        "columns": [
          {
            "name": "ProductModelID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ProductModelID"
          },
          {
            "name": "ProductDescriptionID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ProductDescriptionID",
            "displayOrdinal": 1
          },
          {
            "name": "Culture",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Culture",
            "displayOrdinal": 2
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 3
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.ProductModelProductDescription",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_ProductModelProductDescription\" = Source{[Schema=\"SalesLT\",Item=\"ProductModelProductDescription\"]}[Data] ",
                "in ",
                "#\"SalesLT_ProductModelProductDescription\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.SalesOrderDetail",
        "description": "All data from SalesLT.SalesOrderDetail",
        "columns": [
          {
            "name": "SalesOrderID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "SalesOrderID"
          },
          {
            "name": "SalesOrderDetailID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "SalesOrderDetailID",
            "displayOrdinal": 1
          },
          {
            "name": "OrderQty",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "OrderQty",
            "displayOrdinal": 2
          },
          {
            "name": "ProductID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ProductID",
            "displayOrdinal": 3
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "isNullable": false,
            "sourceColumn": "UnitPrice",
            "displayOrdinal": 4
          },
          {
            "name": "UnitPriceDiscount",
            "dataType": "decimal",
            "isNullable": false,
            "sourceColumn": "UnitPriceDiscount",
            "displayOrdinal": 5
          },
          {
            "name": "LineTotal",
            "dataType": "decimal",
            "isNullable": false,
            "sourceColumn": "LineTotal",
            "displayOrdinal": 6
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 7
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 8
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.SalesOrderDetail",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_SalesOrderDetail\" = Source{[Schema=\"SalesLT\",Item=\"SalesOrderDetail\"]}[Data] ",
                "in ",
                "#\"SalesLT_SalesOrderDetail\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.SalesOrderHeader",
        "description": "All data from SalesLT.SalesOrderHeader",
        "columns": [
          {
            "name": "SalesOrderID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "SalesOrderID"
          },
          {
            "name": "RevisionNumber",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "RevisionNumber",
            "displayOrdinal": 1
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "OrderDate",
            "displayOrdinal": 2
          },
          {
            "name": "DueDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "DueDate",
            "displayOrdinal": 3
          },
          {
            "name": "ShipDate",
            "dataType": "dateTime",
            "sourceColumn": "ShipDate",
            "displayOrdinal": 4
          },
          {
            "name": "Status",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "Status",
            "displayOrdinal": 5
          },
          {
            "name": "OnlineOrderFlag",
            "dataType": "boolean",
            "isNullable": false,
            "sourceColumn": "OnlineOrderFlag",
            "displayOrdinal": 6
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "SalesOrderNumber",
            "displayOrdinal": 7
          },
          {
            "name": "PurchaseOrderNumber",
            "dataType": "string",
            "sourceColumn": "PurchaseOrderNumber",
            "displayOrdinal": 8
          },
          {
            "name": "AccountNumber",
            "dataType": "string",
            "sourceColumn": "AccountNumber",
            "displayOrdinal": 9
          },
          {
            "name": "CustomerID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "CustomerID",
            "displayOrdinal": 10
          },
          {
            "name": "ShipToAddressID",
            "dataType": "int64",
            "sourceColumn": "ShipToAddressID",
            "displayOrdinal": 11
          },
          {
            "name": "BillToAddressID",
            "dataType": "int64",
            "sourceColumn": "BillToAddressID",
            "displayOrdinal": 12
          },
          {
            "name": "ShipMethod",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "ShipMethod",
            "displayOrdinal": 13
          },
          {
            "name": "CreditCardApprovalCode",
            "dataType": "string",
            "sourceColumn": "CreditCardApprovalCode",
            "displayOrdinal": 14
          },
          {
            "name": "SubTotal",
            "dataType": "decimal",
            "isNullable": false,
            "sourceColumn": "SubTotal",
            "displayOrdinal": 15
          },
          {
            "name": "TaxAmt",
            "dataType": "decimal",
            "isNullable": false,
            "sourceColumn": "TaxAmt",
            "displayOrdinal": 16
          },
          {
            "name": "Freight",
            "dataType": "decimal",
            "isNullable": false,
            "sourceColumn": "Freight",
            "displayOrdinal": 17
          },
          {
            "name": "TotalDue",
            "dataType": "decimal",
            "isNullable": false,
            "sourceColumn": "TotalDue",
            "displayOrdinal": 18
          },
          {
            "name": "Comment",
            "dataType": "string",
            "sourceColumn": "Comment",
            "displayOrdinal": 19
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 20
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 21
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.SalesOrderHeader",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_SalesOrderHeader\" = Source{[Schema=\"SalesLT\",Item=\"SalesOrderHeader\"]}[Data] ",
                "in ",
                "#\"SalesLT_SalesOrderHeader\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.authorhashtag_graph",
        "description": "All data from pbist_twitter.authorhashtag_graph",
        "columns": [
          {
            "name": "tweetid",
            "dataType": "string",
            "sourceColumn": "tweetid"
          },
          {
            "name": "author",
            "dataType": "string",
            "sourceColumn": "author",
            "displayOrdinal": 1
          },
          {
            "name": "authorcolor",
            "dataType": "string",
            "sourceColumn": "authorcolor",
            "displayOrdinal": 2
          },
          {
            "name": "hashtag",
            "dataType": "string",
            "sourceColumn": "hashtag",
            "displayOrdinal": 3
          },
          {
            "name": "hashtagcolor",
            "dataType": "string",
            "sourceColumn": "hashtagcolor",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.authorhashtag_graph",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_authorhashtag_graph\" = Source{[Schema=\"pbist_twitter\",Item=\"authorhashtag_graph\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_authorhashtag_graph\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.authormention_graph",
        "description": "All data from pbist_twitter.authormention_graph",
        "columns": [
          {
            "name": "tweetid",
            "dataType": "string",
            "sourceColumn": "tweetid"
          },
          {
            "name": "author",
            "dataType": "string",
            "sourceColumn": "author",
            "displayOrdinal": 1
          },
          {
            "name": "authorcolor",
            "dataType": "string",
            "sourceColumn": "authorcolor",
            "displayOrdinal": 2
          },
          {
            "name": "mention",
            "dataType": "string",
            "sourceColumn": "mention",
            "displayOrdinal": 3
          },
          {
            "name": "mentioncolor",
            "dataType": "string",
            "sourceColumn": "mentioncolor",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.authormention_graph",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_authormention_graph\" = Source{[Schema=\"pbist_twitter\",Item=\"authormention_graph\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_authormention_graph\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.configuration",
        "description": "All data from pbist_twitter.configuration",
        "columns": [
          {
            "name": "id",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "id"
          },
          {
            "name": "configuration_group",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "configuration_group",
            "displayOrdinal": 1
          },
          {
            "name": "configuration_subgroup",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "configuration_subgroup",
            "displayOrdinal": 2
          },
          {
            "name": "name",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "name",
            "displayOrdinal": 3
          },
          {
            "name": "value",
            "dataType": "string",
            "sourceColumn": "value",
            "displayOrdinal": 4
          },
          {
            "name": "visible",
            "dataType": "boolean",
            "isNullable": false,
            "sourceColumn": "visible",
            "displayOrdinal": 5
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.configuration",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_configuration\" = Source{[Schema=\"pbist_twitter\",Item=\"configuration\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_configuration\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.entityinitialcount",
        "description": "All data from pbist_twitter.entityinitialcount",
        "columns": [
          {
            "name": "entityname",
            "dataType": "string",
            "sourceColumn": "entityname"
          },
          {
            "name": "initialcount",
            "dataType": "int64",
            "sourceColumn": "initialcount",
            "displayOrdinal": 1
          },
          {
            "name": "lastcount",
            "dataType": "int64",
            "sourceColumn": "lastcount",
            "displayOrdinal": 2
          },
          {
            "name": "lasttimestamp",
            "dataType": "dateTime",
            "sourceColumn": "lasttimestamp",
            "displayOrdinal": 3
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.entityinitialcount",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_entityinitialcount\" = Source{[Schema=\"pbist_twitter\",Item=\"entityinitialcount\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_entityinitialcount\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.hashtag_slicer",
        "description": "All data from pbist_twitter.hashtag_slicer",
        "columns": [
          {
            "name": "tweetid",
            "dataType": "string",
            "sourceColumn": "tweetid"
          },
          {
            "name": "facet",
            "dataType": "string",
            "sourceColumn": "facet",
            "displayOrdinal": 1
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.hashtag_slicer",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_hashtag_slicer\" = Source{[Schema=\"pbist_twitter\",Item=\"hashtag_slicer\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_hashtag_slicer\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.mention_slicer",
        "description": "All data from pbist_twitter.mention_slicer",
        "columns": [
          {
            "name": "tweetid",
            "dataType": "string",
            "sourceColumn": "tweetid"
          },
          {
            "name": "facet",
            "dataType": "string",
            "sourceColumn": "facet",
            "displayOrdinal": 1
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.mention_slicer",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_mention_slicer\" = Source{[Schema=\"pbist_twitter\",Item=\"mention_slicer\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_mention_slicer\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.minimum_tweets",
        "description": "All data from pbist_twitter.minimum_tweets",
        "columns": [
          {
            "name": "MinimumTweets",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "MinimumTweets"
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.minimum_tweets",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_minimum_tweets\" = Source{[Schema=\"pbist_twitter\",Item=\"minimum_tweets\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_minimum_tweets\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.ssas_jobs",
        "description": "All data from pbist_twitter.ssas_jobs",
        "columns": [
          {
            "name": "id",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "id"
          },
          {
            "name": "startTime",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "startTime",
            "displayOrdinal": 1
          },
          {
            "name": "endTime",
            "dataType": "dateTime",
            "sourceColumn": "endTime",
            "displayOrdinal": 2
          },
          {
            "name": "statusMessage",
            "dataType": "string",
            "sourceColumn": "statusMessage",
            "displayOrdinal": 3
          },
          {
            "name": "lastCount",
            "dataType": "int64",
            "sourceColumn": "lastCount",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.ssas_jobs",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_ssas_jobs\" = Source{[Schema=\"pbist_twitter\",Item=\"ssas_jobs\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_ssas_jobs\""
              ]
            }
          }
        ]
      },
      {
        "name": "sysdiagrams",
        "description": "All data from sysdiagrams",
        "columns": [
          {
            "name": "name",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "name"
          },
          {
            "name": "principal_id",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "principal_id",
            "displayOrdinal": 1
          },
          {
            "name": "diagram_id",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "diagram_id",
            "displayOrdinal": 2
          },
          {
            "name": "version",
            "dataType": "int64",
            "sourceColumn": "version",
            "displayOrdinal": 3
          },
          {
            "name": "definition",
            "dataType": "binary",
            "sourceColumn": "definition",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "sysdiagrams",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"dbo_sysdiagrams\" = Source{[Schema=\"dbo\",Item=\"sysdiagrams\"]}[Data] ",
                "in ",
                "#\"dbo_sysdiagrams\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.tweets_normalized",
        "description": "All data from pbist_twitter.tweets_normalized",
        "columns": [
          {
            "name": "masterid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "masterid"
          },
          {
            "name": "mentions",
            "dataType": "int64",
            "sourceColumn": "mentions",
            "displayOrdinal": 1
          },
          {
            "name": "hashtags",
            "dataType": "int64",
            "sourceColumn": "hashtags",
            "displayOrdinal": 2
          },
          {
            "name": "tweet",
            "dataType": "string",
            "sourceColumn": "tweet",
            "displayOrdinal": 3
          },
          {
            "name": "twitterhandle",
            "dataType": "string",
            "sourceColumn": "twitterhandle",
            "displayOrdinal": 4
          },
          {
            "name": "usernumber",
            "dataType": "string",
            "sourceColumn": "usernumber",
            "displayOrdinal": 5
          },
          {
            "name": "sentiment",
            "dataType": "double",
            "sourceColumn": "sentiment",
            "displayOrdinal": 6
          },
          {
            "name": "sentimentbin",
            "dataType": "double",
            "sourceColumn": "sentimentbin",
            "displayOrdinal": 7
          },
          {
            "name": "sentimentposneg",
            "dataType": "string",
            "sourceColumn": "sentimentposneg",
            "displayOrdinal": 8
          },
          {
            "name": "lang",
            "dataType": "string",
            "sourceColumn": "lang",
            "displayOrdinal": 9
          },
          {
            "name": "accounttag",
            "dataType": "string",
            "sourceColumn": "accounttag",
            "displayOrdinal": 10
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.tweets_normalized",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_tweets_normalized\" = Source{[Schema=\"pbist_twitter\",Item=\"tweets_normalized\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_tweets_normalized\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.tweets_processed",
        "description": "All data from pbist_twitter.tweets_processed",
        "columns": [
          {
            "name": "tweetid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "tweetid"
          },
          {
            "name": "dateorig",
            "dataType": "dateTime",
            "sourceColumn": "dateorig",
            "displayOrdinal": 1
          },
          {
            "name": "hourofdate",
            "dataType": "dateTime",
            "sourceColumn": "hourofdate",
            "displayOrdinal": 2
          },
          {
            "name": "minuteofdate",
            "dataType": "dateTime",
            "sourceColumn": "minuteofdate",
            "displayOrdinal": 3
          },
          {
            "name": "latitude",
            "dataType": "double",
            "sourceColumn": "latitude",
            "displayOrdinal": 4
          },
          {
            "name": "longitude",
            "dataType": "double",
            "sourceColumn": "longitude",
            "displayOrdinal": 5
          },
          {
            "name": "masterid",
            "dataType": "string",
            "sourceColumn": "masterid",
            "displayOrdinal": 6
          },
          {
            "name": "retweet",
            "dataType": "string",
            "sourceColumn": "retweet",
            "displayOrdinal": 7
          },
          {
            "name": "username",
            "dataType": "string",
            "sourceColumn": "username",
            "displayOrdinal": 8
          },
          {
            "name": "usernumber",
            "dataType": "string",
            "sourceColumn": "usernumber",
            "displayOrdinal": 9
          },
          {
            "name": "image_url",
            "dataType": "string",
            "sourceColumn": "image_url",
            "displayOrdinal": 10
          },
          {
            "name": "authorimage_url",
            "dataType": "string",
            "sourceColumn": "authorimage_url",
            "displayOrdinal": 11
          },
          {
            "name": "direction",
            "dataType": "string",
            "sourceColumn": "direction",
            "displayOrdinal": 12
          },
          {
            "name": "favorited",
            "dataType": "int64",
            "sourceColumn": "favorited",
            "displayOrdinal": 13
          },
          {
            "name": "user_followers",
            "dataType": "int64",
            "sourceColumn": "user_followers",
            "displayOrdinal": 14
          },
          {
            "name": "user_friends",
            "dataType": "int64",
            "sourceColumn": "user_friends",
            "displayOrdinal": 15
          },
          {
            "name": "user_favorites",
            "dataType": "int64",
            "sourceColumn": "user_favorites",
            "displayOrdinal": 16
          },
          {
            "name": "user_totaltweets",
            "dataType": "int64",
            "sourceColumn": "user_totaltweets",
            "displayOrdinal": 17
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.tweets_processed",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_tweets_processed\" = Source{[Schema=\"pbist_twitter\",Item=\"tweets_processed\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_tweets_processed\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.twitter_query",
        "description": "All data from pbist_twitter.twitter_query",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "Id"
          },
          {
            "name": "IsAdvanced",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "IsAdvanced",
            "displayOrdinal": 1
          },
          {
            "name": "QueryString",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "QueryString",
            "displayOrdinal": 2
          },
          {
            "name": "TweetId",
            "dataType": "string",
            "sourceColumn": "TweetId",
            "displayOrdinal": 3
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.twitter_query",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_twitter_query\" = Source{[Schema=\"pbist_twitter\",Item=\"twitter_query\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_twitter_query\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.twitter_query_details",
        "description": "All data from pbist_twitter.twitter_query_details",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "Id"
          },
          {
            "name": "ReadableId",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ReadableId",
            "displayOrdinal": 1
          },
          {
            "name": "Operator",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Operator",
            "displayOrdinal": 2
          },
          {
            "name": "Operand",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Operand",
            "displayOrdinal": 3
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.twitter_query_details",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_twitter_query_details\" = Source{[Schema=\"pbist_twitter\",Item=\"twitter_query_details\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_twitter_query_details\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.twitter_query_readable",
        "description": "All data from pbist_twitter.twitter_query_readable",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "Id"
          },
          {
            "name": "QueryId",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "QueryId",
            "displayOrdinal": 1
          },
          {
            "name": "QueryReadable",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "QueryReadable",
            "displayOrdinal": 2
          },
          {
            "name": "Query",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Query",
            "displayOrdinal": 3
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.twitter_query_readable",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_twitter_query_readable\" = Source{[Schema=\"pbist_twitter\",Item=\"twitter_query_readable\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_twitter_query_readable\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.vGetAllCategories",
        "description": "All data from SalesLT.vGetAllCategories",
        "columns": [
          {
            "name": "ParentProductCategoryName",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "ParentProductCategoryName"
          },
          {
            "name": "ProductCategoryName",
            "dataType": "string",
            "sourceColumn": "ProductCategoryName",
            "displayOrdinal": 1
          },
          {
            "name": "ProductCategoryID",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryID",
            "displayOrdinal": 2
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.vGetAllCategories",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_vGetAllCategories\" = Source{[Schema=\"SalesLT\",Item=\"vGetAllCategories\"]}[Data] ",
                "in ",
                "#\"SalesLT_vGetAllCategories\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.vProductAndDescription",
        "description": "All data from SalesLT.vProductAndDescription",
        "columns": [
          {
            "name": "ProductID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ProductID"
          },
          {
            "name": "Name",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Name",
            "displayOrdinal": 1
          },
          {
            "name": "ProductModel",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "ProductModel",
            "displayOrdinal": 2
          },
          {
            "name": "Culture",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Culture",
            "displayOrdinal": 3
          },
          {
            "name": "Description",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Description",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.vProductAndDescription",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_vProductAndDescription\" = Source{[Schema=\"SalesLT\",Item=\"vProductAndDescription\"]}[Data] ",
                "in ",
                "#\"SalesLT_vProductAndDescription\""
              ]
            }
          }
        ]
      },
      {
        "name": "SalesLT.vProductModelCatalogDescription",
        "description": "All data from SalesLT.vProductModelCatalogDescription",
        "columns": [
          {
            "name": "ProductModelID",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ProductModelID"
          },
          {
            "name": "Name",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Name",
            "displayOrdinal": 1
          },
          {
            "name": "Summary",
            "dataType": "string",
            "sourceColumn": "Summary",
            "displayOrdinal": 2
          },
          {
            "name": "Manufacturer",
            "dataType": "string",
            "sourceColumn": "Manufacturer",
            "displayOrdinal": 3
          },
          {
            "name": "Copyright",
            "dataType": "string",
            "sourceColumn": "Copyright",
            "displayOrdinal": 4
          },
          {
            "name": "ProductURL",
            "dataType": "string",
            "sourceColumn": "ProductURL",
            "displayOrdinal": 5
          },
          {
            "name": "WarrantyPeriod",
            "dataType": "string",
            "sourceColumn": "WarrantyPeriod",
            "displayOrdinal": 6
          },
          {
            "name": "WarrantyDescription",
            "dataType": "string",
            "sourceColumn": "WarrantyDescription",
            "displayOrdinal": 7
          },
          {
            "name": "NoOfYears",
            "dataType": "string",
            "sourceColumn": "NoOfYears",
            "displayOrdinal": 8
          },
          {
            "name": "MaintenanceDescription",
            "dataType": "string",
            "sourceColumn": "MaintenanceDescription",
            "displayOrdinal": 9
          },
          {
            "name": "Wheel",
            "dataType": "string",
            "sourceColumn": "Wheel",
            "displayOrdinal": 10
          },
          {
            "name": "Saddle",
            "dataType": "string",
            "sourceColumn": "Saddle",
            "displayOrdinal": 11
          },
          {
            "name": "Pedal",
            "dataType": "string",
            "sourceColumn": "Pedal",
            "displayOrdinal": 12
          },
          {
            "name": "BikeFrame",
            "dataType": "string",
            "sourceColumn": "BikeFrame",
            "displayOrdinal": 13
          },
          {
            "name": "Crankset",
            "dataType": "string",
            "sourceColumn": "Crankset",
            "displayOrdinal": 14
          },
          {
            "name": "PictureAngle",
            "dataType": "string",
            "sourceColumn": "PictureAngle",
            "displayOrdinal": 15
          },
          {
            "name": "PictureSize",
            "dataType": "string",
            "sourceColumn": "PictureSize",
            "displayOrdinal": 16
          },
          {
            "name": "ProductPhotoID",
            "dataType": "string",
            "sourceColumn": "ProductPhotoID",
            "displayOrdinal": 17
          },
          {
            "name": "Material",
            "dataType": "string",
            "sourceColumn": "Material",
            "displayOrdinal": 18
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "displayOrdinal": 19
          },
          {
            "name": "ProductLine",
            "dataType": "string",
            "sourceColumn": "ProductLine",
            "displayOrdinal": 20
          },
          {
            "name": "Style",
            "dataType": "string",
            "sourceColumn": "Style",
            "displayOrdinal": 21
          },
          {
            "name": "RiderExperience",
            "dataType": "string",
            "sourceColumn": "RiderExperience",
            "displayOrdinal": 22
          },
          {
            "name": "rowguid",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "rowguid",
            "displayOrdinal": 23
          },
          {
            "name": "ModifiedDate",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "ModifiedDate",
            "displayOrdinal": 24
          }
        ],
        "partitions": [
          {
            "name": "SalesLT.vProductModelCatalogDescription",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"SalesLT_vProductModelCatalogDescription\" = Source{[Schema=\"SalesLT\",Item=\"vProductModelCatalogDescription\"]}[Data] ",
                "in ",
                "#\"SalesLT_vProductModelCatalogDescription\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.vw_authorhashtag_graph",
        "description": "All data from pbist_twitter.vw_authorhashtag_graph",
        "columns": [
          {
            "name": "Tweet Id",
            "dataType": "string",
            "sourceColumn": "Tweet Id"
          },
          {
            "name": "Author",
            "dataType": "string",
            "sourceColumn": "Author",
            "displayOrdinal": 1
          },
          {
            "name": "Author Color",
            "dataType": "string",
            "sourceColumn": "Author Color",
            "displayOrdinal": 2
          },
          {
            "name": "Hashtag",
            "dataType": "string",
            "sourceColumn": "Hashtag",
            "displayOrdinal": 3
          },
          {
            "name": "Hashtag Color",
            "dataType": "string",
            "sourceColumn": "Hashtag Color",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.vw_authorhashtag_graph",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_vw_authorhashtag_graph\" = Source{[Schema=\"pbist_twitter\",Item=\"vw_authorhashtag_graph\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_vw_authorhashtag_graph\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.vw_authormention_graph",
        "description": "All data from pbist_twitter.vw_authormention_graph",
        "columns": [
          {
            "name": "Tweet Id",
            "dataType": "string",
            "sourceColumn": "Tweet Id"
          },
          {
            "name": "Author",
            "dataType": "string",
            "sourceColumn": "Author",
            "displayOrdinal": 1
          },
          {
            "name": "Author Color",
            "dataType": "string",
            "sourceColumn": "Author Color",
            "displayOrdinal": 2
          },
          {
            "name": "Mention",
            "dataType": "string",
            "sourceColumn": "Mention",
            "displayOrdinal": 3
          },
          {
            "name": "Mention Color",
            "dataType": "string",
            "sourceColumn": "Mention Color",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.vw_authormention_graph",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_vw_authormention_graph\" = Source{[Schema=\"pbist_twitter\",Item=\"vw_authormention_graph\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_vw_authormention_graph\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.vw_configuration",
        "description": "All data from pbist_twitter.vw_configuration",
        "columns": [
          {
            "name": "id",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "id"
          },
          {
            "name": "configuration group",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "configuration group",
            "displayOrdinal": 1
          },
          {
            "name": "configuration subgroup",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "configuration subgroup",
            "displayOrdinal": 2
          },
          {
            "name": "name",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "name",
            "displayOrdinal": 3
          },
          {
            "name": "value",
            "dataType": "string",
            "sourceColumn": "value",
            "displayOrdinal": 4
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.vw_configuration",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_vw_configuration\" = Source{[Schema=\"pbist_twitter\",Item=\"vw_configuration\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_vw_configuration\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.vw_hashtag_slicer",
        "description": "All data from pbist_twitter.vw_hashtag_slicer",
        "columns": [
          {
            "name": "Tweet Id",
            "dataType": "string",
            "sourceColumn": "Tweet Id"
          },
          {
            "name": "Facet",
            "dataType": "string",
            "sourceColumn": "Facet",
            "displayOrdinal": 1
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.vw_hashtag_slicer",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_vw_hashtag_slicer\" = Source{[Schema=\"pbist_twitter\",Item=\"vw_hashtag_slicer\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_vw_hashtag_slicer\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.vw_mention_slicer",
        "description": "All data from pbist_twitter.vw_mention_slicer",
        "columns": [
          {
            "name": "Tweet Id",
            "dataType": "string",
            "sourceColumn": "Tweet Id"
          },
          {
            "name": "Facet",
            "dataType": "string",
            "sourceColumn": "Facet",
            "displayOrdinal": 1
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.vw_mention_slicer",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_vw_mention_slicer\" = Source{[Schema=\"pbist_twitter\",Item=\"vw_mention_slicer\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_vw_mention_slicer\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.vw_minimum_tweets",
        "description": "All data from pbist_twitter.vw_minimum_tweets",
        "columns": [
          {
            "name": "Minimum Tweets",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "Minimum Tweets"
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.vw_minimum_tweets",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_vw_minimum_tweets\" = Source{[Schema=\"pbist_twitter\",Item=\"vw_minimum_tweets\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_vw_minimum_tweets\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.vw_tweets_normalized",
        "description": "All data from pbist_twitter.vw_tweets_normalized",
        "columns": [
          {
            "name": "Master Id",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Master Id"
          },
          {
            "name": "Mentions",
            "dataType": "int64",
            "sourceColumn": "Mentions",
            "displayOrdinal": 1
          },
          {
            "name": "Hashtags",
            "dataType": "int64",
            "sourceColumn": "Hashtags",
            "displayOrdinal": 2
          },
          {
            "name": "Tweet",
            "dataType": "string",
            "sourceColumn": "Tweet",
            "displayOrdinal": 3
          },
          {
            "name": "Twitter Handle",
            "dataType": "string",
            "sourceColumn": "Twitter Handle",
            "displayOrdinal": 4
          },
          {
            "name": "User Number",
            "dataType": "string",
            "sourceColumn": "User Number",
            "displayOrdinal": 5
          },
          {
            "name": "Sentiment",
            "dataType": "double",
            "sourceColumn": "Sentiment",
            "displayOrdinal": 6
          },
          {
            "name": "Sentiment Bin",
            "dataType": "double",
            "sourceColumn": "Sentiment Bin",
            "displayOrdinal": 7
          },
          {
            "name": "Sentiment Positive/Negative",
            "dataType": "string",
            "sourceColumn": "Sentiment Positive/Negative",
            "displayOrdinal": 8
          },
          {
            "name": "Language",
            "dataType": "string",
            "sourceColumn": "Language",
            "displayOrdinal": 9
          },
          {
            "name": "Account Tag",
            "dataType": "string",
            "sourceColumn": "Account Tag",
            "displayOrdinal": 10
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.vw_tweets_normalized",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_vw_tweets_normalized\" = Source{[Schema=\"pbist_twitter\",Item=\"vw_tweets_normalized\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_vw_tweets_normalized\""
              ]
            }
          }
        ]
      },
      {
        "name": "pbist_twitter.vw_tweets_processed",
        "description": "All data from pbist_twitter.vw_tweets_processed",
        "columns": [
          {
            "name": "Tweet Id",
            "dataType": "string",
            "isNullable": false,
            "sourceColumn": "Tweet Id"
          },
          {
            "name": "Original Date",
            "dataType": "dateTime",
            "sourceColumn": "Original Date",
            "displayOrdinal": 1
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "displayOrdinal": 2
          },
          {
            "name": "Hours",
            "dataType": "dateTime",
            "sourceColumn": "Hours",
            "displayOrdinal": 3
          },
          {
            "name": "Minutes",
            "dataType": "dateTime",
            "sourceColumn": "Minutes",
            "displayOrdinal": 4
          },
          {
            "name": "Latitude",
            "dataType": "double",
            "sourceColumn": "Latitude",
            "displayOrdinal": 5
          },
          {
            "name": "Longitude",
            "dataType": "double",
            "sourceColumn": "Longitude",
            "displayOrdinal": 6
          },
          {
            "name": "Master Id",
            "dataType": "string",
            "sourceColumn": "Master Id",
            "displayOrdinal": 7
          },
          {
            "name": "Retweet",
            "dataType": "string",
            "sourceColumn": "Retweet",
            "displayOrdinal": 8
          },
          {
            "name": "Username",
            "dataType": "string",
            "sourceColumn": "Username",
            "displayOrdinal": 9
          },
          {
            "name": "User Number",
            "dataType": "string",
            "sourceColumn": "User Number",
            "displayOrdinal": 10
          },
          {
            "name": "Image URL",
            "dataType": "string",
            "sourceColumn": "Image URL",
            "displayOrdinal": 11
          },
          {
            "name": "Author Image URL",
            "dataType": "string",
            "sourceColumn": "Author Image URL",
            "displayOrdinal": 12
          },
          {
            "name": "Direction",
            "dataType": "string",
            "sourceColumn": "Direction",
            "displayOrdinal": 13
          },
          {
            "name": "Favorited",
            "dataType": "int64",
            "sourceColumn": "Favorited",
            "displayOrdinal": 14
          },
          {
            "name": "User Followers",
            "dataType": "int64",
            "sourceColumn": "User Followers",
            "displayOrdinal": 15
          },
          {
            "name": "User Friends",
            "dataType": "int64",
            "sourceColumn": "User Friends",
            "displayOrdinal": 16
          },
          {
            "name": "User Favourites",
            "dataType": "int64",
            "sourceColumn": "User Favourites",
            "displayOrdinal": 17
          },
          {
            "name": "User Total Tweets",
            "dataType": "int64",
            "sourceColumn": "User Total Tweets",
            "displayOrdinal": 18
          }
        ],
        "partitions": [
          {
            "name": "pbist_twitter.vw_tweets_processed",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\", ",
                "#\"pbist_twitter_vw_tweets_processed\" = Source{[Schema=\"pbist_twitter\",Item=\"vw_tweets_processed\"]}[Data] ",
                "in ",
                "#\"pbist_twitter_vw_tweets_processed\""
              ]
            }
          }
        ]
      },
      {
        "name": "Mbased",
        "columns": [
          {
            "name": "ProductModelIDMin",
            "dataType": "int64",
            "sourceColumn": "ProductModelIDMin",
            "alternateOf": {
              "baseColumn": {
                "table": "SalesLT.ProductModel",
                "column": "ProductModelID"
              },
              "summarization": "sum"
            }
          },
          {
            "name": "NameCount",
            "dataType": "string",
            "sourceColumn": "NameCount",
            "alternateOf": {
              "baseColumn": {
                "table": "SalesLT.ProductModel",
                "column": "Name"
              },
              "summarization": "count"
            }
          },
          {
            "name": "CatalogDescription",
            "dataType": "string",
            "sourceColumn": "CatalogDescription",
            "alternateOf": {
              "baseColumn": {
                "table": "SalesLT.ProductModel",
                "column": "CatalogDescription"
              }
            }
          },
          {
            "name": "rowguidCount",
            "dataType": "string",
            "sourceColumn": "rowguidCount",
            "alternateOf": {
              "baseColumn": {
                "table": "SalesLT.ProductModel",
                "column": "rowguid"
              },
              "summarization": "count"
            }
          }
        ],
        "partitions": [
          {
            "name": "MbasedPartition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let ",
                "Source = #\"SqlServer analytics-db-server.database.windows.net analytics_db\",",
                "#\"SalesLT_ProductModel\" = Source{[Schema=\"SalesLT\",Item=\"ProductModel\"]}[Data],",
                "#\"Selected Columns\" = Table.SelectColumns(#\"SalesLT_ProductModel\", {\"ProductModelID\",\"Name\",\"CatalogDescription\",\"rowguid\"}),",
                "#\"Grouped Rows\" = Table.Group(#\"Selected Columns\", {\"CatalogDescription\"}, {{\"ProductModelIDMin\", each List.Min([ProductModelID])},{\"NameCount\", each List.Count([Name])},{\"rowguidCount\", each List.Count([rowguid])}})",
                "in ",
                "#\"Grouped Rows\""
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "7c054876-137a-4199-848c-0f16db97ecdc",
        "fromTable": "pbist_twitter.authorhashtag_graph",
        "fromColumn": "tweetid",
        "toTable": "pbist_twitter.tweets_processed",
        "toColumn": "tweetid"
      },
      {
        "name": "ae20e8a9-d7e5-45a1-a005-8263e6ae1645",
        "fromTable": "pbist_twitter.authormention_graph",
        "fromColumn": "tweetid",
        "toTable": "pbist_twitter.tweets_processed",
        "toColumn": "tweetid"
      },
      {
        "name": "1d97a94e-26fe-4043-82b4-6d5e50347443",
        "fromTable": "pbist_twitter.hashtag_slicer",
        "fromColumn": "tweetid",
        "toTable": "pbist_twitter.tweets_processed",
        "toColumn": "tweetid"
      },
      {
        "name": "6b2a609a-6a9c-46a3-a930-eebc700d539c",
        "fromTable": "pbist_twitter.mention_slicer",
        "fromColumn": "tweetid",
        "toTable": "pbist_twitter.tweets_processed",
        "toColumn": "tweetid"
      },
      {
        "name": "79f46f1f-acfa-4ff5-8a98-6c0b41f4c284",
        "fromTable": "pbist_twitter.tweets_processed",
        "fromColumn": "masterid",
        "toTable": "pbist_twitter.tweets_normalized",
        "toColumn": "masterid"
      },
      {
        "name": "5ade980c-7641-44e9-beab-ad6583361884",
        "fromTable": "SalesLT.CustomerAddress",
        "fromColumn": "AddressID",
        "toTable": "SalesLT.Address",
        "toColumn": "AddressID"
      },
      {
        "name": "5372273a-45c7-4c78-91ae-4794b935c4b1",
        "fromTable": "SalesLT.CustomerAddress",
        "fromColumn": "CustomerID",
        "toTable": "SalesLT.Customer",
        "toColumn": "CustomerID"
      },
      {
        "name": "e99ef12c-28ee-48e4-baab-3dc008ebcb3e",
        "fromTable": "SalesLT.Product",
        "fromColumn": "ProductCategoryID",
        "toTable": "SalesLT.ProductCategory",
        "toColumn": "ProductCategoryID"
      },
      {
        "name": "c0c3d01e-2e74-4314-a6b7-6a82823aa385",
        "fromTable": "SalesLT.Product",
        "fromColumn": "ProductModelID",
        "toTable": "SalesLT.ProductModel",
        "toColumn": "ProductModelID"
      },
      {
        "name": "e39c3bb9-2d26-4857-8968-85f46db18892",
        "fromTable": "SalesLT.ProductModelProductDescription",
        "fromColumn": "ProductDescriptionID",
        "toTable": "SalesLT.ProductDescription",
        "toColumn": "ProductDescriptionID"
      },
      {
        "name": "c9826436-d544-4cff-8cc6-65797b07b96e",
        "fromTable": "SalesLT.ProductModelProductDescription",
        "fromColumn": "ProductModelID",
        "toTable": "SalesLT.ProductModel",
        "toColumn": "ProductModelID"
      },
      {
        "name": "7d0e997f-2461-4bee-8ef2-3e0a01c73f32",
        "fromTable": "SalesLT.SalesOrderDetail",
        "fromColumn": "ProductID",
        "toTable": "SalesLT.Product",
        "toColumn": "ProductID"
      },
      {
        "name": "3048e251-025f-484c-8966-ff1e89e1a7e2",
        "fromTable": "SalesLT.SalesOrderDetail",
        "fromColumn": "SalesOrderID",
        "toTable": "SalesLT.SalesOrderHeader",
        "toColumn": "SalesOrderID"
      },
      {
        "name": "30a69256-9c1f-47ab-9acf-3f0846ccf7d2",
        "fromTable": "SalesLT.SalesOrderHeader",
        "fromColumn": "BillToAddressID",
        "toTable": "SalesLT.Address",
        "toColumn": "AddressID"
      },
      {
        "name": "b4cbf3f7-e134-476d-9849-11c41b40152a",
        "fromTable": "SalesLT.SalesOrderHeader",
        "fromColumn": "ShipToAddressID",
        "toTable": "SalesLT.Address",
        "toColumn": "AddressID",
        "isActive": false
      },
      {
        "name": "0d2c0e1c-a7c1-498c-a591-86c760a71901",
        "fromTable": "SalesLT.SalesOrderHeader",
        "fromColumn": "CustomerID",
        "toTable": "SalesLT.Customer",
        "toColumn": "CustomerID"
      }
    ],
    "annotations": [
      {
        "name": "ASW-DEFAULT-DIAGRAM",
        "value": "{\"Version\":1,\"Name\":\"default\",\"Tables\":[{\"TableName\":\"SalesLT.SalesOrderHeader\",\"X\":910,\"Y\":910,\"Z\":1,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.SalesOrderDetail\",\"X\":1210,\"Y\":910,\"Z\":2,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.Address\",\"X\":910,\"Y\":1210,\"Z\":3,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.Customer\",\"X\":910,\"Y\":610,\"Z\":4,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.CustomerAddress\",\"X\":1210,\"Y\":1210,\"Z\":5,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.Product\",\"X\":1210,\"Y\":610,\"Z\":6,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.ProductModel\",\"X\":610,\"Y\":610,\"Z\":37,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.ProductCategory\",\"X\":610,\"Y\":910,\"Z\":7,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.ProductModelProductDescription\",\"X\":610,\"Y\":1210,\"Z\":8,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.ProductDescription\",\"X\":610,\"Y\":1510,\"Z\":9,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.tweets_processed\",\"X\":310,\"Y\":310,\"Z\":36,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.mention_slicer\",\"X\":610,\"Y\":310,\"Z\":10,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.hashtag_slicer\",\"X\":310,\"Y\":610,\"Z\":11,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.authormention_graph\",\"X\":910,\"Y\":310,\"Z\":12,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.authorhashtag_graph\",\"X\":310,\"Y\":910,\"Z\":13,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.tweets_normalized\",\"X\":1210,\"Y\":310,\"Z\":14,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.vw_tweets_processed\",\"X\":310,\"Y\":1210,\"Z\":15,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.vw_tweets_normalized\",\"X\":310,\"Y\":1510,\"Z\":16,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.vw_minimum_tweets\",\"X\":910,\"Y\":1510,\"Z\":17,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.vw_mention_slicer\",\"X\":1210,\"Y\":1510,\"Z\":18,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.vw_hashtag_slicer\",\"X\":1510,\"Y\":310,\"Z\":19,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.vw_configuration\",\"X\":1510,\"Y\":610,\"Z\":20,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.vw_authormention_graph\",\"X\":1510,\"Y\":910,\"Z\":21,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.vw_authorhashtag_graph\",\"X\":1510,\"Y\":1210,\"Z\":22,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.vProductModelCatalogDescription\",\"X\":1510,\"Y\":1510,\"Z\":23,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.vProductAndDescription\",\"X\":10,\"Y\":10,\"Z\":24,\"Width\":225,\"Height\":275},{\"TableName\":\"SalesLT.vGetAllCategories\",\"X\":10,\"Y\":310,\"Z\":25,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.twitter_query_readable\",\"X\":10,\"Y\":610,\"Z\":26,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.twitter_query_details\",\"X\":10,\"Y\":910,\"Z\":27,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.twitter_query\",\"X\":10,\"Y\":1210,\"Z\":28,\"Width\":225,\"Height\":275},{\"TableName\":\"sysdiagrams\",\"X\":10,\"Y\":1510,\"Z\":29,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.ssas_jobs\",\"X\":10,\"Y\":1810,\"Z\":30,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.minimum_tweets\",\"X\":310,\"Y\":10,\"Z\":31,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.entityinitialcount\",\"X\":310,\"Y\":1810,\"Z\":32,\"Width\":225,\"Height\":275},{\"TableName\":\"pbist_twitter.configuration\",\"X\":610,\"Y\":10,\"Z\":33,\"Width\":225,\"Height\":275},{\"TableName\":\"ErrorLog\",\"X\":610,\"Y\":1810,\"Z\":34,\"Width\":225,\"Height\":275},{\"TableName\":\"BuildVersion\",\"X\":910,\"Y\":10,\"Z\":35,\"Width\":225,\"Height\":275},{\"TableName\":\"Mbased\",\"X\":200,\"Y\":200,\"Z\":37,\"Width\":225,\"Height\":275}]}"
      }
    ]
  }
}